### PR TITLE
#3 WIP Add local users table. Need to secure API.

### PR DESCRIPTION
**Pull request by mikelax**
Addresses #3 
Just need to secure the POST /users API. Can't figure out for sure if we can get an access token within the scope of a Rule, so maybe just have to send shared secret in payload to be validated with custom middleware or inside route itself?

### CODE REVIEW

**Comment by mikelax** [comment]
@nazar can you show me the example in this branch of how to update the Games (or messages) with the userId from the access token. It's the `sub` attribute in the token.
After the express-jwt middleware I think it would be accessible with `req.user.sub`.

**Comment by nazar** [comment]
Hey @mikelax ,

The `context` object [here](https://github.com/mikelax/forgingadventures/blob/master/api/schemas/game.js#L57) (and other graphql resolvers) contains both the `req` and `res` Express objects. The token info should be available here on the `req` object.

In Match we have a [middleware](https://github.com/WhoSay/dataslinger/blob/master/app/middleware/getUser.js) that detects the token and fetches the user object from the database and adds it to the `req` object, from where we access it further down in the route implementation code.

HTH

**Review by nazar — APPROVED** [review]
:120%:

**Comment by mikelax** [comment]
@nazar  I updated this PR to add the `userId` attribute to the `input` graphql object. 
I made a service instead of middleware as "for now" I didn't want to have to do a db hit for a user lookup on *every* graphql request when the majority of them will most likely be reads.

I think that we might be able to create a new function to do the user lookup and amend the `input` all in a single function if we want to refactor later.

**Pull request merged**
