### PR TITLE
#114 WIP for start of Joi schemas for character attributes.

### PR DESCRIPTION
**Pull request by mikelax**
@nazar  Here are a couple of starter Joi schemas. 
Would appropriate next steps be to: 
* Create migration to add nullable attributes column to characters table
* Refactor create / update character mutations to use this new column?

### CODE REVIEW

**Comment by nazar** [comment]
Hey @mikelax - the Join schema looks 👍 

>Create migration to add nullable attributes column to characters table

We'll have to consider how normalised the `characters` columns should be. Should we have columns for `traits`, `health` etc or should the Joi schema describe a single JSONB column that contains all the character's details? A lot of that depends on how common base traits are and whether they work the same way across games: for example (a made up one) DnD health might be an INT but BnB (made up game) might have health that is broken into two fields.

I  am tempted to put everything in a single JSONB column but that feels a bit reckless to me!

>Refactor create / update character mutations to use this new column?

👍

**Comment by mikelax** [comment]
Cool thx @nazar. 
I was thinking all the data from the joi schema would go into a single jsonb field. 

I think it will be too hard to try and match up fields between game systems. 

There *might* be some overlap with “d20” based systems, but there will be other games that are totally different. Ie maybe don’t even have health at all (for example).

**Comment by nazar** [comment]
>I was thinking all the data from the joi schema would go into a single jsonb field.

👍 ❤️ 

>I think it will be too hard to try and match up fields between game systems

☝️

**Comment by mikelax** [comment]
merging this PR. will do rest of work in #125 PR

**Pull request merged**
