### PR TITLE
Refs #153 - Implement Audit Trail History for Character Changes

### PR DESCRIPTION
**Pull request by nazar**
Opening this for preview/testing - API level validations for character create/edit are still wip

### CODE REVIEW

**Comment by mikelax** [comment]
hey @nazar  man, you are getting fast on this work!!! 
I was thinking about this task this am while walking the dog. Here are a couple of thoughts. 

- Should we break up the existing `character_details` column into two or more fields? This would allow us to more easily add audit history for only a set of fields. ie. if the user updates the `Background Information`, or adds an Item (still need to add Equipment field) should this cause a snapshot? 

After typing and thinking about it a bit more, maybe that is actually fine, it potentially will eat up a bit of storage, ie. if you update a single number field (xp) that will snapshot all the textareas like background, etc. What do you think? 

Do we need to worry about "versions". ie. let's say we roll out this PR, then next week we add two more fields to the character, what happens now that there could potentially be rows in the history table that don't match. Or would adding a new field in the migration update any records in the history table as well?

**Comment by nazar** [comment]
>After typing and thinking about it a bit more, maybe that is actually fine, it potentially will eat up a bit of storage, ie. if you update a single number field (xp) that will snapshot all the textareas like background, etc. What do you think?

Good point! I thought about storing diffs or partials in the table but was slightly concerned that might limit our options in how to display differences in the future. Storing a snapshot is the simplest for now and as for DB storage, I think PG has a set size per db table so the gain, if any, between storing a diff vs snapshot are negligible. 

>Do we need to worry about "versions". ie. let's say we roll out this PR, then next week we add two more fields to the character, what happens now that there could potentially be rows in the history table that don't match. Or would adding a new field in the migration update any records in the history table as well?

I think we have to be careful how we handle versions as there will be issues, like you pointed out, if we update a label's character fields - ideally this shouldn't happen mid game but might be unavoidable.

**Comment by nazar** [comment]
Hey @mikelax - this PR is ready for testing and merging. Please note that a database wipe will probably be required due to the new FK relationships.

I've made some assumptions that data will be available - i.e. `characters.character_details.meta` and `character_logs.character_details.meta` so the migrations cover only schema and not data changes.

**Comment by nazar** [comment]
closes #158 and #153

**Comment by mikelax** [comment]
@nazar  just did some testing, found the following issues:  

1. As the GM, I can not create a game message. I receive this error if I try to post as either the GM, or OOC GM. 
Got the following error:
```
Uncaught (in promise) Error: GraphQL error: Cannot destructure property `labelId` of 'undefined' or 'null'.
    at new ApolloError (:3000/static/js/bundle.js:6300)
    at Object.next (:3000/static/js/bundle.js:4971)
```

**Comment by nazar** [comment]
Nice catch @mikelax - :hawkeye:

**Review by mikelax — APPROVED** [review]
👍 
boom, nice work. this looks great!!

**Pull request merged**
